### ISSUE TITLE
At rest encryption (question)

### ISSUE THREAD

**Issue by martin-hoger** [Nexenta/edgefs#476]
Thank you for a great piece of software. I would like to ask about the encryption feature, I didn't find it much documented. Is it implemented only for the CSI? Can I also use it for NFS without CSI? Is there a page where I could learn more about it?
Thank you!

**Comment by dyusupov** [comment]
@martin-hoger at-rest encryption implemented at data nodes level. Any I/O (from virtualized NFS, S3, iSCSI, NoSQL, SQL, etc interfaces) generates a blockchain-like stream of modified chunks organized in merkle-like binary tree. Each payload block in that tree gets encrypted prior to writing to disk and decrypted upon reads. Unique to a data node key is itself encrypted and securely stored so that only privileged user can gain access to it, but still needs to decrypt it first. I.e. to answer your question, once encryption is enabled (can be per-bucket or per-object) it will transparently work with or without CSI.

**Comment by martin-hoger** [comment]
Dmitry, thank you for your answer! I have one more question, how can I enable the encryption? I played with the "neadm" and "efscli" tools but I didn't find it there. My guess it, that I need to pass a parameter when creating a bucket, but I didn't find any documentation to it.
